# Generated by Django 2.1.2 on 2018-10-25 10:45

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=account.models.get_token, editable=False, unique=True),
        ),
    ]
