# Generated by Django 2.1.2 on 2018-11-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20181103_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('slug',), 'permissions': (('manage_pages', 'Manage pages.'),)},
        ),
    ]
