# Generated by Django 2.1.2 on 2018-11-03 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20181103_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)]),
        ),
    ]
