# Generated by Django 2.1.2 on 2018-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('sort_order',)},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
